### ISSUE TITLE
Apa yang akan kita migrasikan?

### ISSUE THREAD

**Issue by adibfirman** [reactjs-id/website#1]
Dibawah ini adalah checklist apa yang akan kita migrasikan yang sebelumnya dari repository [reactjs.id](https://github.com/reactjs-id/reactjs.id) dimana menggunakan Gatsby, dan sekarang kita akan mencoba ke repository ini dimana menggunakan NextJS.

Untuk gambaran teman - teman sekalian, teman - teman bisa melihat website [reactjs.id](https://reactjs.id) untuk tampilannya.

- [X] Setup Chakra UI - karena sudah _component based_ yang mana mudah untuk di maintain.
- [X] Setup tema (warna dan ukuran text, font name, dan lain sebagainya)
- [x] Setup SEO
- [X] Migrasi komponen _Header_ (TopNavigation); Done by @SamX23  #16 
- [X] Migrasi komponen _Footer_; Done by @hanihusam #13 
- [X] Migrasi _Home_ Page; Done by @adibfirman #26 
- [X] Migrasi _Komunitas_ Page; Done by @alfanfauzy #25 
- [X] Migrasi _Ajukan Topik_ Page; Done by @andriawan #22
- [X] Migrasi _Learning_ Page; Done by @yuhanasy https://github.com/reactjs-id/website/pull/27
- [X] Migrasi _FAQ_ Page; Done by @muhsatrio https://github.com/reactjs-id/website/pull/10

Jika teman - teman menemukan hal yang seharusnya di migrasikan tetapi belum masuk checklist diatas, sangat terbuka sekali untuk menambahkan, Terima Kasih

**Comment by kaliwa** [comment]
saya coba handle setup SEO-nya mas

**Comment by adibfirman** [comment]
> saya coba handle setup SEO-nya mas

Halo mas,
Makasih ya mas udah handle SEO-nya, jangan lupa untuk create issue baru dan mention issue ini ya 👌

**Comment by hanihusam** [comment]
Saya coba ambil yang "Migrasi Komponen _Footer_" Mas

**Comment by adibfirman** [comment]
> Saya coba ambil yang "Migrasi Komponen _Footer_" Mas

Halo mas,
Terima kasih sudah berpartisipasi daln migrasi kali ini, jangan lupa untuk membuat issue, assign ke diri sendiri dan mention issue ini ya mas, terima kasih 👏

**Comment by SamX23** [comment]
Bismillah,
Halo mas, saya boleh coba ambil migrasi header?

**Comment by muhsatrio** [comment]
Halo mas, saya boleh coba ambil migrasi FAQ Page?

**Comment by adibfirman** [comment]
> Bismillah,
> Halo mas, saya boleh coba ambil migrasi component header?

Halo mas,
Silahkan mas, dan jangan lupa untuk create issue dan mention issue ini ya, Terima Kasih 👌

**Comment by andriawan** [comment]
Saya ingin coba masuk dan beradaptasi denagn development Next.js sebelumnya udah pernah handle gatsby. Saya akan coba ambil Migrasi Halaman ajukan topik. Apakah tidak masalah @adibfirman ?

**Comment by adibfirman** [comment]
> Saya ingin coba masuk dan beradaptasi denagn development Next.js sebelumnya udah pernah handle gatsby. Saya akan coba ambil Migrasi Halaman ajukan topik. Apakah tidak masalah @adibfirman ?

Halo mas,
Silahkan banget mas, kita sama sama belajar kok, jangan lupa buat issue dan assign ke diri sendiri ya, ohh iya jangan lupa juga untuk mention issue ini 👌,

**Comment by andriawan** [comment]
> > Saya ingin coba masuk dan beradaptasi denagn development Next.js sebelumnya udah pernah handle gatsby. Saya akan coba ambil Migrasi Halaman ajukan topik. Apakah tidak masalah @adibfirman ?
> 
> Halo mas,
> Silahkan banget mas, kita sama sama belajar kok, jangan lupa buat issue dan assign ke diri sendiri ya, ohh iya jangan lupa juga untuk mention issue ini 👌,

Oke siap mas @adibfirman

**Comment by alfanfauzy** [comment]
Mas @adibfirman izin bantuin utk migrasi yang halaman komunitas . Sepertinya belum masuk ke listnya migrasi dan belum ada yang handle ya ?

**Comment by adibfirman** [comment]
> Mas @adibfirman izin bantuin utk migrasi yang halaman komunitas . Sepertinya belum masuk ke listnya migrasi dan belum ada yang handle ya ?

ohh iyaa sip sip mas, silahkan mas, aku tambahin note diatas dulu yaa, thanks banget udah reminder page ini 🙏

**Comment by alfanfauzy** [comment]
> > Mas @adibfirman izin bantuin utk migrasi yang halaman komunitas . Sepertinya belum masuk ke listnya migrasi dan belum ada yang handle ya ?
> 
> ohh iyaa sip sip mas, silahkan mas, aku tambahin note diatas dulu yaa, thanks banget udah reminder page ini 🙏

Izin saya create issue ya mas, nnti sya mention disini ya .

**Comment by yuhanasy** [comment]
apakah halaman Home dan Learning sudah ada yang mengerjakan?

**Comment by kaliwa** [comment]
> apakah halaman Home dan Learning sudah ada yang mengerjakan?

halaman Home sudah mas, bisa dicek di #9 .

kalau halaman Learning karena belum masuk list mungkin mas @adibfirman bisa membantu.

**Comment by adibfirman** [comment]
Ohh iya halaman learning belum saya masukan kan ke TODO, bentar yaa, boleh mas @yuhanasy kalau mau ambil 👌

**Comment by alfanfauzy** [comment]
mas @adibfirman , yang di Halaman FAQ saya lihat ada minor di _mark_ kalau ada link perlu di enhance kah ?? Kalau iya , boleh saya take over ?

**Comment by muhsatrio** [comment]
> mas @adibfirman , yang di Halaman FAQ saya lihat ada minor di _mark_ kalau ada link perlu di enhance kah ?? Kalau iya , boleh saya take over ?

Itu awalnya sudah saya buat custom css nya, tapi kata mas @resir014 sementara mengikuti component chakra-ui apa adanya dulu mas @alfanfauzy

**Comment by adibfirman** [comment]
> > mas @adibfirman , yang di Halaman FAQ saya lihat ada minor di _mark_ kalau ada link perlu di enhance kah ?? Kalau iya , boleh saya take over ?
> 
> FYI awalnya sudah saya implement custom css nya untuk mark link, tapi kata mas @resir014 sementara mengikuti component chakra-ui apa adanya dulu mas @alfanfauzy. Bisa dicek mungkin di history PR saya

iya bener kita pake Chakra - UI sepenuhnya, dan untuk mark link saya sedikit komentar di #25 yaa, thanks

**Comment by alfanfauzy** [comment]
> FYI awalnya sudah saya implement custom css nya untuk mark link, tapi kata mas @resir014 sementara mengikuti component chakra-ui apa adanya dulu mas @alfanfauzy. Bisa dicek mungkin di history PR saya

Siap mas . 

> iya bener kita pake Chakra - UI sepenuhnya, dan untuk mark link saya sedikit komentar di #25 yaa, thanks

Saya coba implementasikan dlu masukan di #25 ya mas

**Comment by adibfirman** [comment]
Wow its done, within a month i think just a couple of weeks 😎, makasih banyak semua atas kontribusi-nya aku close yaa issue-nya kalau ada teman - teman yang menemukan masalah dan ada yang mau di improve open issue aja yaa thanks 👋
